spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
jpa:
  database-plataform: org.hibernate.dialiect.H2Dialect
  properties:
    hibernate:
      show_sql: true
      format_sql: true
h2:
  console:
    enable: true